dist: focal
language: node_js
node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "16"
   - "14"
   - "12"

before_install: npm i -g npm@8.5.5

script:
   - node --version
   - npm --version
   - commitlint-travis
   - npm run standards
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
