language: node_js
node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "12"
   - "10"
   - "8"

before_install: npm i -g npm@6.13.4

script:
   - node --version
   - npm --version
   - commitlint-travis
   - grunt standards
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
